version: '3'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - ./assembly/db:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${DB_PORT}:${DB_PORT}
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - ${PGADMIN_PORT}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  app:
    build: assembly/app
    container_name: app
    command: bash -c "
      while !</dev/tcp/db/5432; do sleep 1;
      done; alembic upgrade head
      && mypy .
      && pytest tests/
      && uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "
    volumes:
      - ./project:/usr/src/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: always
    depends_on:
      - db
    env_file:
      - app.env
  nginx:
    build: assembly/nginx
    container_name: nginx
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    restart: always
    depends_on:
      - app

volumes:
  db:
  app:
